name: test

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - '.swiftlint.yml'
      - '**/*.swift'
  pull_request:
    branches: [ main ]
    paths:
      - '.swiftlint.yml'
      - '**/*.swift'

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Run tests
      run: swift test -v
